from __future__ import annotations

import json
from pathlib import Path
import subprocess
import sys
from tempfile import TemporaryDirectory
import unittest

import yaml


SCRIPTS = Path(__file__).resolve().parent.parent / "scripts"
APPLY = SCRIPTS / "apply.py"
VALIDATE = SCRIPTS / "validate.py"


def artifact(root: Path, artifact_id: str, frontmatter: str, body: str = "") -> None:
    path = root / f"{artifact_id}.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        f"---\nid: {artifact_id}\n{frontmatter}---\n{body}",
        encoding="utf-8",
    )


class ApplyScaleTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = TemporaryDirectory()
        self.world = Path(self.temporary.name)
        (self.world / "world.yaml").write_text(
            "kernel_version: '0.12'\n",
            encoding="utf-8",
        )
        artifact(
            self.world,
            "entities/verrow-family",
            "kind: entity\ntype: community/guild\nname: The Verrow millers\n"
            "tags: [grain, river]\nstatus: canon\n",
        )
        artifact(
            self.world,
            "actions/milling",
            "kind: entity\ntype: action/practice\nname: Milling\n"
            "tags: [miller, grain]\nstatus: draft\n",
        )
        artifact(
            self.world,
            "entities/north-gate",
            "kind: entity\ntype: place/gate\nname: North Gate\nstatus: draft\n",
        )

    def tearDown(self) -> None:
        self.temporary.cleanup()

    def run_apply(self, *arguments: str, input_data: str | None = None) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            [sys.executable, str(APPLY), str(self.world), *arguments],
            input=input_data,
            text=True,
            capture_output=True,
            check=False,
        )

    def test_find_matches_name_tags_and_zero_is_success(self) -> None:
        by_name = self.run_apply("--find", "MILLER")
        by_tag = self.run_apply("--find", "grain")
        absent = self.run_apply("--find", "zzzz")

        self.assertEqual(by_name.returncode, 0, by_name.stderr)
        self.assertIn("entities/verrow-family", by_name.stdout)
        self.assertIn("actions/milling", by_name.stdout)
        self.assertEqual(by_tag.stdout.count("\n  "), 2)
        self.assertEqual(absent.returncode, 0)
        self.assertEqual(absent.stdout, '0 match(es) for "zzzz":\n')

    def test_find_limit_reports_truncation(self) -> None:
        result = self.run_apply("--find", "grain", "--limit", "1")

        self.assertEqual(result.returncode, 0)
        self.assertIn("2 match(es)", result.stdout)
        self.assertIn("truncated", result.stdout)
        self.assertEqual(result.stdout.count("\n  "), 1)

    def test_index_filters_compose_and_type_is_a_glob(self) -> None:
        result = self.run_apply(
            "--index",
            "--kind", "entity",
            "--type", "place/*",
            "--status", "draft",
        )

        self.assertEqual(result.returncode, 0)
        self.assertIn("artifacts: 1", result.stdout)
        self.assertIn("entities/north-gate", result.stdout)
        self.assertNotIn("entities/verrow-family", result.stdout)

    def test_reindex_and_each_successful_mutation_refresh_index(self) -> None:
        reindexed = self.run_apply("--reindex")
        index_path = self.world / "INDEX.md"

        self.assertEqual(reindexed.returncode, 0, reindexed.stdout)
        first_index = index_path.read_text(encoding="utf-8")
        self.assertIn("GENERATED BY apply.py. DO NOT EDIT BY HAND", first_index)
        self.assertIn("## Entity", first_index)
        self.assertIn("## Entity", first_index)

        payload = json.dumps([
            {
                "id": "ideas/night-law",
                "kind": "idea",
                "name": "The Night Law",
                "status": "draft",
                "body": "No gate stands unguarded.",
            }
        ])
        written = self.run_apply("--session", "scale-test", input_data=payload)
        self.assertEqual(written.returncode, 0, written.stdout + written.stderr)
        self.assertIn("ideas/night-law", index_path.read_text(encoding="utf-8"))

        promoted = self.run_apply("--promote", "ideas/night-law")
        self.assertEqual(promoted.returncode, 0, promoted.stdout)
        self.assertIn("Validation:", promoted.stdout)
        self.assertIn("status: canon", (self.world / "ideas/night-law.md").read_text(encoding="utf-8"))
        self.assertIn("ideas/night-law", index_path.read_text(encoding="utf-8"))

        rejected = self.run_apply("--reject", "ideas/night-law")
        self.assertEqual(rejected.returncode, 0, rejected.stdout)
        self.assertIn("Validation:", rejected.stdout)
        self.assertFalse((self.world / "ideas/night-law.md").exists())
        self.assertNotIn("ideas/night-law", index_path.read_text(encoding="utf-8"))

    def test_single_item_collections_are_valid_yaml(self) -> None:
        payload = json.dumps([
            {
                "id": "ideas/single-list",
                "kind": "idea",
                "name": "Single list regression",
                "tags": ["regression"],
                "where": ["entities/north-gate"],
                "metadata": {"source": "test"},
            }
        ])

        written = self.run_apply("--session", "single-list-test", input_data=payload)
        self.assertEqual(written.returncode, 0, written.stdout + written.stderr)

        text = (self.world / "ideas/single-list.md").read_text(encoding="utf-8")
        self.assertNotIn("where: -", text)
        frontmatter = yaml.safe_load(text.split("---", 2)[1])
        self.assertEqual(frontmatter["tags"], ["regression"])
        self.assertEqual(frontmatter["where"], ["entities/north-gate"])
        self.assertEqual(frontmatter["metadata"], {"source": "test"})

    def test_generated_index_is_ignored_by_validator(self) -> None:
        self.assertEqual(self.run_apply("--reindex").returncode, 0)
        result = subprocess.run(
            [sys.executable, str(VALIDATE), str(self.world)],
            text=True,
            capture_output=True,
            check=False,
        )

        self.assertNotIn("INDEX: no YAML frontmatter", result.stdout)
        self.assertNotIn("INDEX: no YAML frontmatter", result.stderr)

    def test_existing_failure_exit_codes_remain_nonzero(self) -> None:
        promote = self.run_apply("--promote", "entities/missing")
        reject = self.run_apply("--reject", "entities/missing")

        self.assertEqual(promote.returncode, 1)
        self.assertEqual(reject.returncode, 1)


class ValidatorCardinalityTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = TemporaryDirectory()
        self.world = Path(self.temporary.name)
        artifact(
            self.world,
            "types/part_of",
            "kind: type\nconstraints:\n  roles_required: [part, whole]\n"
            "  roles_unique: [whole]\n",
        )
        artifact(
            self.world,
            "types/part_of/province",
            "kind: type\n",
        )
        artifact(
            self.world,
            "types/participates",
            "kind: type\nconstraints:\n  roles_required: [action]\n"
            "  roles_unique: [action]\n  role_types: {action: [action]}\n",
        )
        artifact(self.world, "types/action", "kind: type\napplies_to_kind: entity\n")
        for artifact_id, artifact_type in (
            ("entities/realm", None),
            ("entities/north", None),
            ("entities/vale", None),
            ("actions/siege", "action"),
            ("actions/raid", "action"),
        ):
            body = "kind: entity\n"
            if artifact_type:
                body += f"type: {artifact_type}\n"
            artifact(self.world, artifact_id, body)

    def tearDown(self) -> None:
        self.temporary.cleanup()

    def run_validate(self) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            [sys.executable, str(VALIDATE), str(self.world)],
            text=True,
            capture_output=True,
            check=False,
        )

    def test_nary_part_of_is_valid_and_child_inherits_unique_whole(self) -> None:
        artifact(
            self.world,
            "relations/provinces",
            "kind: relation\ntype: part_of/province\nmembers:\n"
            "  - {id: entities/realm, role: whole}\n"
            "  - {id: entities/north, role: part}\n"
            "  - {id: entities/vale, role: part}\n",
        )
        result = self.run_validate()
        self.assertEqual(result.returncode, 0, result.stdout)

    def test_duplicate_unique_role_errors_or_downgrades_under_fiat(self) -> None:
        artifact(
            self.world,
            "relations/broken-provinces",
            "kind: relation\ntype: part_of\nmembers:\n"
            "  - {id: entities/realm, role: whole}\n"
            "  - {id: entities/north, role: whole}\n"
            "  - {id: entities/vale, role: part}\n",
        )
        result = self.run_validate()
        self.assertEqual(result.returncode, 1)
        self.assertIn("role 'whole' at most once", result.stdout)

        path = self.world / "relations/broken-provinces.md"
        path.write_text(path.read_text(encoding="utf-8").replace("type: part_of\n", "type: part_of\nfiat: true\n"), encoding="utf-8")
        result = self.run_validate()
        self.assertEqual(result.returncode, 0, result.stdout)
        self.assertIn("NOTICE", result.stdout)

    def test_unique_action_and_malformed_declaration_are_rejected(self) -> None:
        artifact(
            self.world,
            "relations/two-actions",
            "kind: relation\ntype: participates\nmembers:\n"
            "  - {id: actions/siege, role: action}\n"
            "  - {id: actions/raid, role: action}\n",
        )
        result = self.run_validate()
        self.assertEqual(result.returncode, 1)
        self.assertIn("role 'action' at most once", result.stdout)

        artifact(self.world, "types/bad", "kind: type\nconstraints:\n  roles_unique: whole\n")
        result = self.run_validate()
        self.assertEqual(result.returncode, 1)
        self.assertIn("roles_unique must be a list", result.stdout)

    def test_repeated_directed_roles_warn_without_banning_shared_anchors(self) -> None:
        artifact(
            self.world,
            "types/governs",
            "kind: type\nlens:\n  as: edge\n  direction: [governor, domain]\n",
        )
        artifact(self.world, "types/governs/local", "kind: type\n")
        artifact(
            self.world,
            "types/governs/undirected",
            "kind: type\nlens:\n  color: '#8899aa'\n",
        )
        for artifact_id in (
            "entities/governor-a",
            "entities/governor-b",
            "entities/domain-a",
            "entities/domain-b",
        ):
            artifact(self.world, artifact_id, "kind: entity\n")
        artifact(
            self.world,
            "relations/ambiguous-governance",
            "kind: relation\ntype: governs/local\nmembers:\n"
            "  - {id: entities/governor-a, role: governor}\n"
            "  - {id: entities/domain-a, role: domain}\n"
            "  - {id: entities/governor-b, role: governor}\n"
            "  - {id: entities/domain-b, role: domain}\n",
        )
        artifact(
            self.world,
            "relations/shared-governor",
            "kind: relation\ntype: governs\nmembers:\n"
            "  - {id: entities/governor-a, role: governor}\n"
            "  - {id: entities/domain-a, role: domain}\n"
            "  - {id: entities/domain-b, role: domain}\n",
        )
        artifact(
            self.world,
            "relations/shared-domain",
            "kind: relation\ntype: governs\nmembers:\n"
            "  - {id: entities/governor-a, role: governor}\n"
            "  - {id: entities/governor-b, role: governor}\n"
            "  - {id: entities/domain-a, role: domain}\n",
        )
        artifact(
            self.world,
            "relations/nearest-lens-is-undirected",
            "kind: relation\ntype: governs/undirected\nmembers:\n"
            "  - {id: entities/governor-a, role: governor}\n"
            "  - {id: entities/domain-a, role: domain}\n"
            "  - {id: entities/governor-b, role: governor}\n"
            "  - {id: entities/domain-b, role: domain}\n",
        )
        artifact(
            self.world,
            "relations/duplicate-entries-are-one-role-member",
            "kind: relation\ntype: governs\nmembers:\n"
            "  - {id: entities/governor-a, role: governor}\n"
            "  - {id: entities/domain-a, role: domain}\n"
            "  - {id: entities/governor-a, role: governor}\n"
            "  - {id: entities/domain-a, role: domain}\n",
        )

        result = self.run_validate()

        self.assertEqual(result.returncode, 0, result.stdout)
        self.assertEqual(result.stdout.count("member order does not pair them"), 1)
        self.assertIn("relations/ambiguous-governance", result.stdout)

    def test_relation_artifacts_can_be_grouped_by_a_higher_order_relation(self) -> None:
        artifact(self.world, "types/governs", "kind: type\n")
        artifact(self.world, "types/governance-system", "kind: type\n")
        artifact(
            self.world,
            "relations/one-jurisdiction",
            "kind: relation\ntype: governs\nmembers:\n"
            "  - {id: entities/realm, role: governor}\n"
            "  - {id: entities/north, role: domain}\n",
        )
        artifact(
            self.world,
            "relations/governance-system",
            "kind: relation\ntype: governance-system\nmembers:\n"
            "  - {id: relations/one-jurisdiction, role: jurisdiction}\n"
            "  - {id: entities/realm, role: scope}\n",
        )

        result = self.run_validate()

        self.assertEqual(result.returncode, 0, result.stdout)
        self.assertNotIn("dangling reference", result.stdout)

    def test_qualitative_one_member_state_value_is_accepted(self) -> None:
        artifact(self.world, "types/state", "kind: type\n")
        artifact(self.world, "types/state/exploration", "kind: type\n")
        artifact(
            self.world,
            "relations/frontier",
            "kind: relation\ntype: state/exploration\nvalue: unexplored\n"
            "members: [{id: entities/north, role: subject}]\n",
        )

        result = self.run_validate()

        self.assertEqual(result.returncode, 0, result.stdout)
        self.assertNotIn("state value", result.stdout)

    def test_state_value_rejects_non_qualitative_or_non_state_use(self) -> None:
        artifact(
            self.world,
            "relations/bad-value",
            "kind: relation\ntype: part_of\nvalue: unexplored\n"
            "members: [{id: entities/realm, role: whole}, {id: entities/north, role: part}]\n",
        )

        result = self.run_validate()

        self.assertEqual(result.returncode, 0, result.stdout)
        self.assertIn("top-level 'value' is reserved", result.stdout)

    def test_state_value_requires_a_non_empty_string(self) -> None:
        artifact(self.world, "types/state", "kind: type\n")
        for suffix, value in (
            ("empty", "''"),
            ("number", "12"),
            ("list", "[unexplored]"),
            ("mapping", "{status: unexplored}"),
        ):
            artifact(
                self.world,
                f"relations/{suffix}-state",
                "kind: relation\ntype: state/exploration\n"
                f"value: {value}\nmembers: [{{id: entities/north, role: subject}}]\n",
            )

        result = self.run_validate()

        self.assertEqual(result.returncode, 0, result.stdout)
        self.assertEqual(result.stdout.count("state value must be a non-empty string"), 4)

    def test_state_value_and_amount_are_mutually_exclusive(self) -> None:
        artifact(self.world, "types/state", "kind: type\n")
        artifact(
            self.world,
            "relations/ambiguous-state",
            "kind: relation\ntype: state/exploration\nvalue: unexplored\n"
            "amount: {value: 12, unit: persons}\n"
            "members: [{id: entities/north, role: subject}]\n",
        )

        result = self.run_validate()

        self.assertEqual(result.returncode, 0, result.stdout)
        self.assertIn("qualitative state value cannot be combined with numeric amount", result.stdout)


if __name__ == "__main__":
    unittest.main()
